version: '3'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - "5432:5432"
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - ./postgrest:/var/lib/postgresql/data